app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses'  => 'entrepreneurshipController@index',
    'as'    => 'entrepreneurship'
]);

Route::get('/all', [
    'uses'  => 'entrepreneurshipController@paginate',
    'as'    => 'all'
]);

// Authentication routes...
Route::get('login', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'login'
]);
Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'logout'
]);

// Registration routes...
Route::get('register', [ 
    'uses'  => 'Auth\AuthController@getRegister',
    'as'    => 'register'
]);
Route::post('register', 'Auth\AuthController@postRegister');


Route::resource('entrepreneurships', 'entrepreneurshipController');

Route::get('profile', [
    'uses'  => 'entrepreneurshipController@postEdit',
    'as'    => 'profile'
]);


Route::get('removeAccount', [
    'uses'  => 'entrepreneurshipController@removeAccount',
    'as'    => 'removeAccount'
]);

Route::get('terms', [
    'uses'  => 'entrepreneurshipController@terms',
    'as'    => 'terms'
]);

Route::get('sendEmail','Auth\PasswordController@getEmail');

Route::post('sendEmail', [ 
    'uses'  => 'Auth\PasswordController@postEmail',
    'as'    => 'sendEmail'
]);
// Route::post('sendEmail','Auth\PasswordController@postEmail');
Route::get('/password/reset/{token}','Auth\PasswordController@getReset');

Route::post('resetPassword/{token}', [ 
    'uses'  => 'Auth\PasswordController@postReset',
    'as'    => 'resetPassword'
]);


// API
Route::group(['prefix' => 'poderoso'], function()
{
    Route::get('/', [
        'uses'  => 'entrepreneurshipController@admin',
        'as'    => 'list'
    ]);

    Route::resource('entrepreneurships', 'entrepreneurshipController');


    Route::get('entrepreneurships/{id}/delete', [
        'uses' => 'entrepreneurshipController@destroy',
        'as' => 'poderoso.entrepreneurships.delete',
    ]);

    Route::get('editentrep/{id}', [ 
        'uses'  => 'entrepreneurshipController@edit',
        'as'    => 'editentrep'
    ]);

    Route::post('editentrep/{id}', [
        'uses'  => 'entrepreneurshipController@update',
        'as'    => 'editentrep'
    ]);



    Route::resource('categories', 'categoriesController');

    Route::get('categories/{id}/delete', [
        'as' => 'poderoso.categories.delete',
        'uses' => 'categoriesController@destroy',
    ]);

    Route::post('categories', [
        'as' => 'categories',
        'uses' => 'categoriesController@store',
    ]);

    Route::resource('cities', 'citiesController');

    Route::get('cities/{id}/delete', [
        'as' => 'poderoso.cities.delete',
        'uses' => 'citiesController@destroy',
    ]);

    Route::post('cities', [
        'as' => 'cities',
        'uses' => 'citiesController@store',
    ]);

    Route::resource('communes', 'communesController');

    Route::get('communes/{id}/delete', [
        'as' => 'poderoso.communes.delete',
        'uses' => 'communesController@destroy',
    ]);

    Route::post('communes', [
        'as' => 'communes',
        'uses' => 'communesController@store',
    ]);

    Route::resource('types', 'typesController');

    Route::get('types/{id}/delete', [
        'as' => 'poderoso.types.delete',
        'uses' => 'typesController@destroy',
    ]);

    Route::post('types', [
        'as' => 'types',
        'uses' => 'typesController@store',
    ]);
});

app/Models/entrepreneurship.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

class entrepreneurship extends Model
{
    
	public $table = "entrepreneurship";
    

	public $fillable = [
	    "user_id",
		"name",
		"email",
		"description",
		"category_id",
		"city_id",
		"commune_id",
		"phone",
		"address",
		"social_media"
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
    ];

	public static $rules = [
	];

    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }
	public function categories()
    {
        return $this->belongsTo('App\Models\categories','category_id');
    }

    public function cities()
    {
        return $this->belongsTo('App\Models\cities','city_id');
    }
    
    public function communes()
    {
        return $this->belongsTo('App\Models\communes','commune_id');
    }
    
    public function entrepreneurship_types()
    {
        return $this->hasMany('App\Models\entrepreneurship_types', 'type_id');
    }

    public function media()
    {
        return $this->belongsTo('App\Models\Media','image_id');
    }

    public function scopeTerm($query, $term)
    {
        if(trim($term) != ""){
            $query->where(\DB::raw("CONCAT(name, address, description)"), 'LIKE', "%$term%");
        }
    }

}

app/Models/entrepreneurship_types.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class entrepreneurship_types extends Model
{
    public $table = "entrepreneurship_types";
    

	public $fillable = [
	    "type_id",
		"entrepreneurship_id"
	];


    public function entrepreneurship()
    {
        return $this->belongsTo('App\Models\entrepreneurship','entrepreneurship_id');
    }

    public function types()
    {
       return $this->hasOne('App\Models\types','id');
    }

}

app/Http/Controllers/entrepreneurshipController.php
<?php namespace App\Http\Controllers;

use App\User;
use App\Models\categories;
use App\Models\types;
use App\Models\cities;
use App\Models\communes;
use App\Models\entrepreneurship_types;
use App\Models\entrepre_types;
use App\Models\entrepreneurship;
use App\Models\Media;
use App\Http\Requests;
use App\Http\Requests\CreateentrepreneurshipRequest;
use App\Http\Requests\UpdateentrepreneurshipRequest;
use App\Libraries\Repositories\entrepreneurshipRepository;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use Response;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Routing\UrlGenerator;
use Illuminate\Support\Facades\Auth;

use Validator;

class entrepreneurshipController extends AppBaseController
{

	/** @var  entrepreneurshipRepository */
	private $entrepreneurshipRepository;

	function __construct(entrepreneurshipRepository $entrepreneurshipRepo)
	{
		$this->entrepreneurshipRepository = $entrepreneurshipRepo;
	}

	/**
	 * Display a listing of the entrepreneurship.
	 *
	 * @return Response
	 */
	public function index()
	{
		$cats = categories::all();
		$typs = types::all();
		$cits = cities::all();
		$coms = communes::all();
		$entrepreneurships = entrepreneurship::where('publish','=','1')->orderBy('created_at', 'desc')->take(4)->get();

		foreach ($entrepreneurships as $key => $value) {
			$value['category'] = $value->categories['name'];
			$value['city'] = $value->cities['name'];
			$value['commune'] = $value->communes['name'];
			$value['owner'] = $value->user;
			$value['image'] = $value->media['path'] . $value->media['name'];
			$value['short_description'] = str_limit($value['description'],150);
			if($value['social_media'] && $value['social_media'] != ''){
				$parsed = parse_url($value['social_media']);
				if (empty($parsed['scheme'])) {
					$value['social_media'] = 'http://' . ltrim($value['social_media'], '/');
				}
			}
		}
		return View('entrepreneurships.index', compact(['entrepreneurships']))->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
	}

	public function admin()
	{
		if (Auth::user())
		{
			$cats = categories::all();
			$typs = types::all();
			$cits = cities::all();
			$coms = communes::all();
	        $types = entrepreneurship_types::all();
	        $entrepreneurships = $this->entrepreneurshipRepository->paginate(10);
	        foreach ($entrepreneurships as $key => $value) {
	            $value['category'] = $value->categories['name'];
	            $value['city'] = $value->cities['name'];
	            $value['commune'] = $value->communes['name'];
	            $value['type'] = $types;
	            $value['short_description'] = str_limit($value['description'],50);
	        }
    
        // var_dump($entrepreneurships);
        	return View('entrepreneurships.admin', compact(['entrepreneurships']))->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
    	}
    	else{

		return redirect(route('entrepreneurships.index'));

		}
	}

	/**
	 * Display a listing of the entrepreneurship.
	 *
	 * @return Response
	 */
	public function paginate(Request $request)
	{
		$cats = categories::all();
		$typs = types::all();
		$cits = cities::all();
		$coms = communes::all();
		$term = $request->get('term') ? $request->get('term') : '';
		$entrepreneurships = entrepreneurship::where('publish','=','1')->term($request->get('term'))->orderBy('created_at', 'desc')->paginate(5);
		foreach ($entrepreneurships as $key => $value) {
			$value['category'] = $value->categories['name'];
			$value['city'] = $value->cities['name'];
			$value['commune'] = $value->communes['name'];
			$value['owner'] = $value->user;
			$value['image'] = $value->media['path'] . $value->media['name'];
			$value['short_description'] = str_limit($value['description'],150);
			if($value['social_media'] && $value['social_media'] != ''){
				$parsed = parse_url($value['social_media']);
				if (empty($parsed['scheme'])) {
					$value['social_media'] = 'http://' . ltrim($value['social_media'], '/');
				}
			}
		}
		return View('entrepreneurships.viewall', compact(['entrepreneurships', 'term']))->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
	}

    public function getCreate()
    {
        $cats = categories::all();
        $typs = types::all();
        $cits = cities::all();
        $coms = communes::all();
        return  view('entrepreneurships.create')->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
        
    }


	protected function create_entrepreneurship(Request $request,$id_register) {
		$data=$request->all();
		$validator=Validator::make($data, [
		    'description' => 'required',
		    'category' => 'required',
		    'phone' => 'required|max:50',
		]);

		if ($validator->fails()) {
		    $this->throwValidationException(
		        $request, $validator
		    );
		}

		$entrepr= entrepreneurships::create([
		    'id' => $id_register,
		    'name' => $data['name'],
		    'description' => $data['description'],
		    'category_id' => $data['category'],
		    'phone' => $data['phone'],
		    'address' => $data['address'],
		]);

      return $entrepr;
    }


	/**
	 * Show the form for creating a new entrepreneurship.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('entrepreneurships.create');
	}

	/**
	 * Store a newly created entrepreneurship in storage.
	 *
	 * @param CreateentrepreneurshipRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateentrepreneurshipRequest $request)
	{
		$input = $request->all();

		$entrepreneurship = $this->entrepreneurshipRepository->create($input);

		Flash::success('Emprendimiento guardado correctamente.');

		return redirect(route('entrepreneurships.index'));
	}

	/**
	 * Display the specified entrepreneurship.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$entrepreneurship = $this->entrepreneurshipRepository->find($id);

		if(empty($entrepreneurship))
		{
			Flash::error('Emprendimiento no encontrado.');

			return redirect(route('entrepreneurships.index'));
		}

		return view('entrepreneurships.show')->with('entrepreneurship', $entrepreneurship);
	}

	/**
	 * Show the form for editing the specified entrepreneurship.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit(Request $request, $id)
	{
		if (Auth::user())
		{
	 		$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();
	        
			$entrepreneurship = entrepreneurship::find($id);
			$entrepreneurship['category'] = $entrepreneurship->categories['id'];
			$entrepreneurship['city'] = $entrepreneurship->cities['id'];
			$entrepreneurship['commune'] = $entrepreneurship->communes['id'];
			$entrepreneurship['image'] = url() . '/' . $entrepreneurship->media['path'] . $entrepreneurship->media['name'];
				

			if(empty($entrepreneurship))
			{
				Flash::error('Emprendimiento no encontrado.');

				return redirect(route('entrepreneurships.index'));
			}

		//$infouser=$request->user()->id;
		//$infoid=$entrepreneurship['id'];

			return view('entrepreneurships.edit')->with('entrepreneurship', $entrepreneurship)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}
		else{

		return redirect(route('entrepreneurships.index'));

		}
	}

	/**
	 * Update the specified entrepreneurship in storage.
	 *
	 * @param  int              $id
	 * @param UpdateentrepreneurshipRequest $request
	 *
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$data=$request->all();
		$validator=Validator::make($data, [
            'e_name' => 'required',
            'description' => 'required',
            'category' => 'required',
            'city' => 'required',
            'commune' => 'required',
            'phone' => 'required|max:50',
            'email' => 'required|email|max:255',
            'image' => 'mimes:jpeg,bmp,png,jpg'
        ]);

        if ($validator->fails()) {
		    $this->throwValidationException(
		        $request, $validator
		    );
		}

		$entrepreneurship = entrepreneurship::find($id);
		
		$data = $request->all();
		$datauser=$request->user();


		$infouser=$request->user()->id;
		$infoid=$entrepreneurship['id'];

		if(isset($data['image'])){
            $this->upload_image($request, $infouser, $infoid);
        }

		$entrepreneurship['name'] = $data['e_name'];
		$entrepreneurship['description'] = $data['description'];
		$entrepreneurship['category_id'] = $data['category'];
		$entrepreneurship['city_id'] = $data['city'];
		$entrepreneurship['commune_id'] = $data['commune'];
		$entrepreneurship['phone'] = $data['phone'];
		$entrepreneurship['email'] = $data['email'];
		$entrepreneurship['address'] = $data['address'];
		$entrepreneurship['social_media'] = $data['social_web'];


	    $entrepreneurship->save($entrepreneurship->toArray());


		Flash::success('Emprendimiento actualizado correctamente.');

		return redirect(route('profile'));
	}

	public function upload_image(Request $request, $user, $entre){
	        $imageName = $user . '_' . $request->file('image')->getFilename() . '.' . $request->file('image')->getClientOriginalExtension();

	        $request->file('image')->move(
	            base_path() . '/public/uploads/images/', $imageName
	        );

	        $image = Media::create([
	            "name"  => $imageName,
	            "path"  => 'uploads/images/',
	            "size"  => '0',
	            "type"  => $request->file('image')->getClientOriginalExtension()
	        ]);

	        $entre = entrepreneurship::find($entre);
	        $entre['image_id'] = $image['id'];
	        $entre->save();

	        return $image;
	}

	public function postEdit(Request $request)
    {
    	if (Auth::user())
		{

	        $infouser=$request->user()->id;
	        $cats = categories::all();
	        $typs = types::all();

resources/views/entrepreneurships/admin.blade.php
@extends('layout')

@section('content')
@include('menu.admin_menu')
    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">entrepreneurships</h1>

        </div>

        <div class="row">
            @if($entrepreneurships->isEmpty())
                <div class="well text-center">No entrepreneurships found.</div>
            @else
                @include('entrepreneurships.table')
            @endif
        </div>

        @include('common.paginate', ['records' => $entrepreneurships])


    </div>
@endsection

resources/views/entrepreneurships/create.blade.php
@extends('layout')

@section('content')
<br />
<br />
<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form class="form-horizontal" role="form" method="POST" action="{{ route('register', []) }}" enctype="multipart/form-data">
            @include('partials/errors')
            <div class="panel panel-default">
                <div class="panel-heading">Hola</div>
                <div class="panel-body">

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.name')</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.description')</label>
                            <div class="col-md-6">
                                <textarea class="form-control" name="description" value="{{ old('description') }}" rows="4"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.category')</label>
                            <div class="col-md-6">
                                <select class="form-control" name="category" value="{{ old('category') }}">
                                    <option selected disable>Elije una categoría</option>
                                     @foreach($cats as $cat)
                                     <option value="{!! $cat->id !!}">
                                        {!! $cat->name !!}
                                     </option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.type')</label>
                            <div class="col-md-6">
                                <select class="form-control" name="type" value="{{ old('type') }}">
                                    <option selected disable>Elije un tipo de iniciativa</option>
                                     @foreach($typs as $typ)
                                     <option value="{!! $typ->id !!}">
                                        {!! $typ->name !!}
                                     </option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.city')</label>
                            <div class="col-md-6">
                                <select class="form-control" name="city" value="{{ old('city') }}">
                                    <option selected disable>Elije una ciudad</option>
                                     @foreach($cits as $cit)
                                     <option value="{!! $cit->id !!}">
                                        {!! $cit->name !!}
                                     </option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.commune')</label>
                            <div class="col-md-6">
                                <select class="form-control" name="commune" value="{{ old('commune') }}">
                                    <option selected disable>Elije una comuna</option>
                                     @foreach($coms as $com)
                                     <option value="{!! $com->id !!}">
                                        {!! $com->name !!}
                                     </option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.phone')</label>
                            <div class="col-md-6">
                                <input type="phone" class="form-control" name="phone" value="{{ old('phone') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.address')</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="address" value="{{ old('address') }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.social_web')</label>
                            <div class="col-md-6">
                                <input type="url" class="form-control" name="social_web" value="{{ old('social_web') }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">@lang('validation.attributes.image')</label>
                            <div class="col-md-6">
                                <input type="file" class="form-control" name="image" value="{{ old('image') }}">
                            </div>
                        </div>
                </div>
            </div>
                    <div class="form-group">
                        <div class="col-md-12 col-md-offset-5">
                            <button type="submit" class="btn btn-primary">
                                @lang('auth.register_button')
                            </button>
                        </div>
                    </div>
            </form>

        </div>
    </div>
</div>
@endsection

resources/views/entrepreneurships/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('user_id', 'User Id:') !!}
	{!! Form::text('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('name', 'Name:') !!}
	{!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('description', 'Description:') !!}
	{!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Category Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('category_id', 'Category Id:') !!}
	{!! Form::text('category_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('type_id', 'Type Id:') !!}
	{!! Form::text('type_id', null, ['class' => 'form-control']) !!}
</div>

<!-- City Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('city_id', 'City Id:') !!}
	{!! Form::text('city_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Commune Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('commune_id', 'Commune Id:') !!}
	{!! Form::text('commune_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('image_id', 'Image Id:') !!}
	{!! Form::text('image_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('phone', 'Phone:') !!}
	{!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Adress Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('address', 'Address:') !!}
	{!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Social Media Url Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('social_media', 'Social Media Url:') !!}
	{!! Form::text('social_media', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/entrepreneurships/index.blade.php
@extends('layout')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="text-center">Últimas iniciativas</h1>
            <!-- <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('entrepreneurships.create') !!}">Add New</a> -->
        </div>

        <div class="row lista">
            @if($entrepreneurships->isEmpty())
                <div class="well text-center">No se encontraron emprendimientos</div>
            @else
                @include('entrepreneurships.list')
            @endif
        </div>
        <div class="row more">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <a href="{{ route('all') }}" class="pull-right">Ver todas</a>
            </div>
        </div>

    </div>
    <script type="text/javascript">
    setTimeout(function(){
        var Things = $('.error');
        for (var i = 0; i < Things.length; i++) {
            if($('.error')[i].innerHTML == "El usuario y la contraseña no coinciden"){
                $('#modalLogin').modal();
                break;
            } else{
                $('.welcome').hide();
                $('#step1').show();
                $('.alert').show();
                $('#modalRegister').modal();
                break;
            }
        };

        var inputs = "#u_username, #u_lastname, #u_email, #u_password, #u_password_confirmation";
        $(inputs).bind('DOMAttrModified textInput input change keypress paste focus',function(data) {
            if($('#u_username').val() !== "" && $('#u_lastname').val() !== "" && $('#u_email').val() !== "" && $('#u_password').val() !== "" && $('#u_password_confirmation').val() !== ""){
                if ($('#u_password').val() === $('#u_password_confirmation').val()) {
                    $('#goToStep1').prop("disabled", false);
                } else{
                    $('#goToStep1').prop("disabled", true);
                }
            } else {
                $('#goToStep1').prop("disabled", true);
            }
        });
    },100);
    </script>
@endsection

resources/views/entrepreneurships/list.blade.php
@foreach($entrepreneurships as $entrepreneurship)
	<div class="entre col-xs-12 col-md-8 col-md-offset-2">
		<div class="col-md-2 col-md-offset-1 img">
			<img src="{!! $entrepreneurship->image !!}" />
		</div>
		<div class="col-xs-12 col-md-8">
			<h3>{!! $entrepreneurship->name !!}</h3>
			<strong>{!! $entrepreneurship->category !!}</strong>
			<p>{!! $entrepreneurship->short_description !!}</p>
			<span class="label label-default" data-toggle="modal" data-target="#modal{!! $entrepreneurship->id !!}">Ver más</span>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade datailEntrepreneurship" id="modal{!! $entrepreneurship->id !!}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					<div class="info">
						<img src="{!! $entrepreneurship->image !!}" />
						<h3>{!! $entrepreneurship->name !!}</h3>
						<strong>{!! $entrepreneurship->category !!}</strong>
						<p>{!! $entrepreneurship->description !!}</p>
					</div>
					<div class="contact">
						<strong>Contacto</strong>
						<div>{!! $entrepreneurship->user->name !!} {!! $entrepreneurship->user->lastname !!}</div>
						<div>Tel: {!! $entrepreneurship->phone !!}</div>
						<div>Dirección: {!! $entrepreneurship->address !!} / {!! $entrepreneurship->city !!}</div>
						<div>{!! $entrepreneurship->email !!}</div>
						@if($entrepreneurship->social_media && $entrepreneurship->social_media != '')
						<div>Web: <a href="{!! $entrepreneurship->social_media !!}" target="_blank">{!! $entrepreneurship->social_media !!}</a></div>
						@endif
					</div>
				</div>
				<!-- <div class="modal-footer">
					<p class="pull-right">
						<strong>Compartir:</strong>
						<span>F</span>
						<span>T</span>
					</p>
				</div> -->
			</div>
		</div>
	</div>
@endforeach

resources/views/entrepreneurships/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('entrepreneurships.show_fields')
</div>
@endsection

resources/views/entrepreneurships/table.blade.php
<table class="table">
    <thead>
    <th>Id</th>
			<th>Name</th>
			<th>Description</th>
			<th>Category</th>
			<th>City</th>
			<th>Commune</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Adress</th>
			<th>Social Media Url</th>
    <th width="50px">Action</th>
    </thead>
    <tbody>

    @foreach($entrepreneurships as $entrepreneurship)
        <tr>
            <td>{!! $entrepreneurship->user_id !!}</td>
			<td>{!! $entrepreneurship->name !!}</td>
			<td>{!! $entrepreneurship->short_description !!}</td>
            <td>{!! $entrepreneurship->category !!}</td>
			<td>{!! $entrepreneurship->city !!}</td>
			<td>{!! $entrepreneurship->commune !!}</td>
			<td>{!! $entrepreneurship->phone !!}</td>
			<td>{!! $entrepreneurship->email !!}</td>
			<td>{!! $entrepreneurship->address !!}</td>
			<td>{!! $entrepreneurship->social_media !!}</td>
            <td>
                <a href="{!! route('poderoso.entrepreneurships.edit', [$entrepreneurship->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('poderoso.entrepreneurships.delete', [$entrepreneurship->id]) !!}" onclick="return confirm('Si elimina el emprendimiento también se eliminará la cuenta a la cuál esta relacionada el emprendimiento. \n¿Está seguro que desea eliminar el emprendimiento?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
    @endforeach
  
    </tbody>
</table>