app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses'  => 'entrepreneurshipController@index',
    'as'    => 'entrepreneurship'
]);

Route::get('/all', [
    'uses'  => 'entrepreneurshipController@paginate',
    'as'    => 'all'
]);

// Authentication routes...
Route::get('login', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'login'
]);
Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'logout'
]);

// Registration routes...
Route::get('register', [ 
    'uses'  => 'Auth\AuthController@getRegister',
    'as'    => 'register'
]);
Route::post('register', 'Auth\AuthController@postRegister');


Route::resource('entrepreneurships', 'entrepreneurshipController');

Route::get('profile', [
    'uses'  => 'entrepreneurshipController@postEdit',
    'as'    => 'profile'
]);


Route::get('removeAccount', [
    'uses'  => 'entrepreneurshipController@removeAccount',
    'as'    => 'removeAccount'
]);

Route::get('terms', [
    'uses'  => 'entrepreneurshipController@terms',
    'as'    => 'terms'
]);

Route::get('sendEmail','Auth\PasswordController@getEmail');

Route::post('sendEmail', [ 
    'uses'  => 'Auth\PasswordController@postEmail',
    'as'    => 'sendEmail'
]);
// Route::post('sendEmail','Auth\PasswordController@postEmail');
Route::get('/password/reset/{token}','Auth\PasswordController@getReset');

Route::post('resetPassword/{token}', [ 
    'uses'  => 'Auth\PasswordController@postReset',
    'as'    => 'resetPassword'
]);


// API
Route::group(['prefix' => 'poderoso'], function()
{
    Route::get('/', [
        'uses'  => 'entrepreneurshipController@admin',
        'as'    => 'list'
    ]);

    Route::resource('entrepreneurships', 'entrepreneurshipController');


    Route::get('entrepreneurships/{id}/delete', [
        'uses' => 'entrepreneurshipController@destroy',
        'as' => 'poderoso.entrepreneurships.delete',
    ]);

    Route::get('editentrep/{id}', [ 
        'uses'  => 'entrepreneurshipController@edit',
        'as'    => 'editentrep'
    ]);

    Route::post('editentrep/{id}', [
        'uses'  => 'entrepreneurshipController@update',
        'as'    => 'editentrep'
    ]);



    Route::resource('categories', 'categoriesController');

    Route::get('categories/{id}/delete', [
        'as' => 'poderoso.categories.delete',
        'uses' => 'categoriesController@destroy',
    ]);

    Route::post('categories', [
        'as' => 'categories',
        'uses' => 'categoriesController@store',
    ]);

    Route::resource('cities', 'citiesController');

    Route::get('cities/{id}/delete', [
        'as' => 'poderoso.cities.delete',
        'uses' => 'citiesController@destroy',
    ]);

    Route::post('cities', [
        'as' => 'cities',
        'uses' => 'citiesController@store',
    ]);

    Route::resource('communes', 'communesController');

    Route::get('communes/{id}/delete', [
        'as' => 'poderoso.communes.delete',
        'uses' => 'communesController@destroy',
    ]);

    Route::post('communes', [
        'as' => 'communes',
        'uses' => 'communesController@store',
    ]);

    Route::resource('types', 'typesController');

    Route::get('types/{id}/delete', [
        'as' => 'poderoso.types.delete',
        'uses' => 'typesController@destroy',
    ]);

    Route::post('types', [
        'as' => 'types',
        'uses' => 'typesController@store',
    ]);
});

app/Http/Controllers/citiesController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreatecitiesRequest;
use App\Http\Requests\UpdatecitiesRequest;
use App\Libraries\Repositories\citiesRepository;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use App\helpers\Helper as Helper;
use Response;
use App\Models\categories;
use App\Models\types;
use App\Models\cities;
use App\Models\communes;
use Illuminate\Support\Facades\Auth;

class citiesController extends AppBaseController
{

	/** @var  citiesRepository */
	private $citiesRepository;

	function __construct(citiesRepository $citiesRepo)
	{
		$this->citiesRepository = $citiesRepo;
	}

	/**
	 * Display a listing of the cities.
	 *
	 * @return Response
	 */
	public function index()
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();

			$cities = $this->citiesRepository->paginate(10);

			return view('cities.index')->with('cities', $cities)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}		
	}

	/**
	 * Show the form for creating a new cities.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('cities.create');
	}

	/**
	 * Store a newly created cities in storage.
	 *
	 * @param CreatecitiesRequest $request
	 *
	 * @return Response
	 */
	
	public function store(CreatecitiesRequest $request)
	{
		

		$input = $request->all();
		$input['slug']=Helper::makeSlug($input['name']);
		$cities = $this->citiesRepository->create($input);

		Flash::success('Ciudad guardada correctamente.');

		return redirect(route('poderoso.cities.index'));
	}


	/**
	 * Display the specified cities.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$cities = $this->citiesRepository->find($id);

		if(empty($cities))
		{
			Flash::error('Ciudad no encontrada.');

			return redirect(route('poderoso.cities.index'));
		}

		return view('cities.show')->with('cities', $cities);
	}

	/**
	 * Show the form for editing the specified cities.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id)
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();
			$cities = $this->citiesRepository->find($id);

			if(empty($cities))
			{
				Flash::error('Ciudad no encontrada.');

				return redirect(route('poderoso.cities.index'));
			}

			return view('cities.edit')->with('cities', $cities)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}	
		else{

			return redirect(route('entrepreneurships.index'));

		}
	}

	/**
	 * Update the specified cities in storage.
	 *
	 * @param  int              $id
	 * @param UpdatecitiesRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdatecitiesRequest $request)
	{
		$cities = $this->citiesRepository->find($id);

		if(empty($cities))
		{
			Flash::error('Ciudad no encontrada.');

			return redirect(route('poderoso.cities.index'));
		}
		$req = $request->all();
		$req['slug']=Helper::makeSlug($req['name']);
		$cities = $this->citiesRepository->updateRich($req, $id);

		Flash::success('Ciudad actualizada correctamente');

		return redirect(route('poderoso.cities.index'));
	}

	/**
	 * Remove the specified cities from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		if (Auth::user())
		{
			$cities = $this->citiesRepository->find($id);

			if(empty($cities))
			{
				Flash::error('Ciudad no encontrada.');

				return redirect(route('poderoso.cities.index'));
			}

			$this->citiesRepository->delete($id);

			Flash::success('Ciudad eliminada correctamente');

			return redirect(route('poderoso.cities.index'));
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}	
	}
}

resources/views/cities/create.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'cities.store']) !!}

        @include('cities.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/cities/edit.blade.php
@extends('layout')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($cities, ['route' => ['poderoso.cities.update', $cities->id], 'method' => 'patch']) !!}

        @include('cities.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/cities/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('name', 'Name:') !!}
	{!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/cities/index.blade.php
@extends('layout')

@section('content')
@include('menu.admin_menu')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            cities
        </div>
        <div class="panel-body">
            <div class="row">
                @include('flash::message')
            </div>

            <div class="row">
                @if($cities->isEmpty())
                    <div class="well text-center">Ciudades no encontradas.</div>
                @else
                <div class="col-lg-12">
                    @include('cities.table')
                </div>
                @endif
            </div>

            @include('common.paginate', ['records' => $cities])

        </div>
    </div>

    <form class="form-horizontal" role="form" method="POST" action="{{ route('cities') }}">
        @include('partials/errors')
        <div class="panel panel-default">
            <div class="panel-heading">@lang('auth.register_title')</div>
            <div class="panel-body">

                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label class="col-md-4 control-label">@lang('validation.attributes.name')</label>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-5">
                        <button type="submit" class="btn btn-primary">
                            @lang('auth.register_button')
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
    </form>
</div>
@endsection

resources/views/cities/indextwo.blade.php
@extends('app')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">cities</h1>
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('cities.create') !!}">Add New</a>
        </div>

        <div class="row">
            @if($cities->isEmpty())
                <div class="well text-center">No cities found.</div>
            @else
                @include('cities.table')
            @endif
        </div>

        @include('common.paginate', ['records' => $cities])


    </div>
@endsection

resources/views/cities/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('cities.show_fields')
</div>
@endsection

resources/views/cities/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $cities->name !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{!! $cities->slug !!}</p>
</div>

resources/views/cities/table.blade.php
<table class="table">
    <thead>
    <th>Name</th>
			<th>Slug</th>
    <th width="50px">Action</th>
    </thead>
    <tbody>
    @foreach($cities as $cities)
        <tr>
            <td>{!! $cities->name !!}</td>
			<td>{!! $cities->slug !!}</td>
            <td>
                <a href="{!! route('poderoso.cities.edit', [$cities->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('poderoso.cities.delete', [$cities->id]) !!}" onclick="return confirm('¿Está seguro que desea eliminar esta ciudad?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>