app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses'  => 'entrepreneurshipController@index',
    'as'    => 'entrepreneurship'
]);

Route::get('/all', [
    'uses'  => 'entrepreneurshipController@paginate',
    'as'    => 'all'
]);

// Authentication routes...
Route::get('login', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'login'
]);
Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'logout'
]);

// Registration routes...
Route::get('register', [ 
    'uses'  => 'Auth\AuthController@getRegister',
    'as'    => 'register'
]);
Route::post('register', 'Auth\AuthController@postRegister');


Route::resource('entrepreneurships', 'entrepreneurshipController');

Route::get('profile', [
    'uses'  => 'entrepreneurshipController@postEdit',
    'as'    => 'profile'
]);


Route::get('removeAccount', [
    'uses'  => 'entrepreneurshipController@removeAccount',
    'as'    => 'removeAccount'
]);

Route::get('terms', [
    'uses'  => 'entrepreneurshipController@terms',
    'as'    => 'terms'
]);

Route::get('sendEmail','Auth\PasswordController@getEmail');

Route::post('sendEmail', [ 
    'uses'  => 'Auth\PasswordController@postEmail',
    'as'    => 'sendEmail'
]);
// Route::post('sendEmail','Auth\PasswordController@postEmail');
Route::get('/password/reset/{token}','Auth\PasswordController@getReset');

Route::post('resetPassword/{token}', [ 
    'uses'  => 'Auth\PasswordController@postReset',
    'as'    => 'resetPassword'
]);


// API
Route::group(['prefix' => 'poderoso'], function()
{
    Route::get('/', [
        'uses'  => 'entrepreneurshipController@admin',
        'as'    => 'list'
    ]);

    Route::resource('entrepreneurships', 'entrepreneurshipController');


    Route::get('entrepreneurships/{id}/delete', [
        'uses' => 'entrepreneurshipController@destroy',
        'as' => 'poderoso.entrepreneurships.delete',
    ]);

    Route::get('editentrep/{id}', [ 
        'uses'  => 'entrepreneurshipController@edit',
        'as'    => 'editentrep'
    ]);

    Route::post('editentrep/{id}', [
        'uses'  => 'entrepreneurshipController@update',
        'as'    => 'editentrep'
    ]);



    Route::resource('categories', 'categoriesController');

    Route::get('categories/{id}/delete', [
        'as' => 'poderoso.categories.delete',
        'uses' => 'categoriesController@destroy',
    ]);

    Route::post('categories', [
        'as' => 'categories',
        'uses' => 'categoriesController@store',
    ]);

    Route::resource('cities', 'citiesController');

    Route::get('cities/{id}/delete', [
        'as' => 'poderoso.cities.delete',
        'uses' => 'citiesController@destroy',
    ]);

    Route::post('cities', [
        'as' => 'cities',
        'uses' => 'citiesController@store',
    ]);

    Route::resource('communes', 'communesController');

    Route::get('communes/{id}/delete', [
        'as' => 'poderoso.communes.delete',
        'uses' => 'communesController@destroy',
    ]);

    Route::post('communes', [
        'as' => 'communes',
        'uses' => 'communesController@store',
    ]);

    Route::resource('types', 'typesController');

    Route::get('types/{id}/delete', [
        'as' => 'poderoso.types.delete',
        'uses' => 'typesController@destroy',
    ]);

    Route::post('types', [
        'as' => 'types',
        'uses' => 'typesController@store',
    ]);
});

app/Http/Controllers/categoriesController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreatecategoriesRequest;
use App\Http\Requests\UpdatecategoriesRequest;
use App\Libraries\Repositories\categoriesRepository;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use App\helpers\Helper as Helper;
use Response;
use App\Models\categories;
use App\Models\types;
use App\Models\cities;
use App\Models\communes;
use Illuminate\Support\Facades\Auth;

class categoriesController extends AppBaseController
{

	/** @var  categoriesRepository */
	private $categoriesRepository;

	function __construct(categoriesRepository $categoriesRepo)
	{
		$this->categoriesRepository = $categoriesRepo;
	}

	/**
	 * Display a listing of the categories.
	 *
	 * @return Response
	 */
	public function index()
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();

			$categories = $this->categoriesRepository->paginate(10);

			return view('categories.index')->with('categories', $categories)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}

		else{

			return redirect(route('entrepreneurships.index'));

		}
	}

	/**
	 * Show the form for creating a new categories.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('categories.create');
	}

	/**
	 * Store a newly created categories in storage.
	 *
	 * @param CreatecategoriesRequest $request
	 *
	 * @return Response
	 */
	public function store(CreatecategoriesRequest $request)
	{
		

		$input = $request->all();
		$input['slug']=Helper::makeSlug($input['name']);
		$categories = $this->categoriesRepository->create($input);

		Flash::success('Categoría guardada correctamente.');

		return redirect(route('poderoso.categories.index'));
	}

	/**
	 * Display the specified categories.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$categories = $this->categoriesRepository->find($id);

		if(empty($categories))
		{
			Flash::error('Categoría no encontrada');

			return redirect(route('poderoso.categories.index'));
		}

		return view('categories.show')->with('categories', $categories);
	}

	/**
	 * Show the form for editing the specified categories.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id)
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();

			$categories = $this->categoriesRepository->find($id);

			if(empty($categories))
			{
				Flash::error('Categoría no encontrada');

				return redirect(route('poderoso.categories.index'));
			}

			return view('categories.edit')->with('categories', $categories)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}
	}

	/**
	 * Update the specified categories in storage.
	 *
	 * @param  int              $id
	 * @param UpdatecategoriesRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdatecategoriesRequest $request)
	{
		$categories = $this->categoriesRepository->find($id);

		if(empty($categories))
		{
			Flash::error('Categoría no encontrada');

			return redirect(route('poderoso.categories.index'));
		}
		$req = $request->all();
		$req['slug']=Helper::makeSlug($req['name']);
		$categories = $this->categoriesRepository->updateRich($req, $id);

		Flash::success('Categoría actualizada correctamente.');

		return redirect(route('poderoso.categories.index'));
	}

	/**
	 * Remove the specified categories from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		if (Auth::user())
		{
			$categories = $this->categoriesRepository->find($id);

			if(empty($categories))
			{
				Flash::error('Categoría no encontrada');

				return redirect(route('poderoso.categories.index'));
			}

			$this->categoriesRepository->delete($id);

			Flash::success('Categoría eliminada correctamente');

			return redirect(route('poderoso.categories.index'));
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}
	}	
}

resources/views/categories/create.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'categories.store']) !!}

        @include('categories.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layout')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($categories, ['route' => ['poderoso.categories.update', $categories->id], 'method' => 'patch']) !!}

        @include('categories.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/categories/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('name', 'Name:') !!}
	{!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/categories/index.blade.php
@extends('layout')

@section('content')
@include('menu.admin_menu')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Categories
        </div>
        <div class="panel-body">
            <div class="row">
                @include('flash::message')
            </div>
            <div class="row">
                @if($categories->isEmpty())
                    <div class="well text-center">Categorías no encontradas.</div>
                @else
                <div class="col-lg-12">
                    @include('categories.table')
                </div>
                @endif
            </div>

            @include('common.paginate', ['records' => $categories])

        </div>
    </div>

    <form class="form-horizontal" role="form" method="POST" action="{{ route('categories') }}">
        @include('partials/errors')
        <div class="panel panel-default">
            <div class="panel-heading">@lang('auth.register_title')</div>
            <div class="panel-body">

                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label class="col-md-4 control-label">@lang('validation.attributes.name')</label>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-5">
                        <button type="submit" class="btn btn-primary">
                            @lang('auth.register_button')
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
    </form>
</div>
@endsection

resources/views/categories/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('categories.show_fields')
</div>
@endsection

resources/views/categories/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $categories->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $categories->name !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{!! $categories->slug !!}</p>
</div>

resources/views/categories/table.blade.php
<table class="table">
    <thead>
    <th>Id</th>
			<th>Name</th>
			<th>Slug</th>
    <th width="50px">Action</th>
    </thead>
    <tbody>
    @foreach($categories as $categories)
        <tr>
            <td>{!! $categories->id !!}</td>
			<td>{!! $categories->name !!}</td>
			<td>{!! $categories->slug !!}</td>
            <td>
                <a href="{!! route('poderoso.categories.edit', [$categories->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('poderoso.categories.delete', [$categories->id]) !!}" onclick="return confirm('¿Está seguro que desea eliminar esta categoría?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>