app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses'  => 'entrepreneurshipController@index',
    'as'    => 'entrepreneurship'
]);

Route::get('/all', [
    'uses'  => 'entrepreneurshipController@paginate',
    'as'    => 'all'
]);

// Authentication routes...
Route::get('login', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'login'
]);
Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'logout'
]);

// Registration routes...
Route::get('register', [ 
    'uses'  => 'Auth\AuthController@getRegister',
    'as'    => 'register'
]);
Route::post('register', 'Auth\AuthController@postRegister');


Route::resource('entrepreneurships', 'entrepreneurshipController');

Route::get('profile', [
    'uses'  => 'entrepreneurshipController@postEdit',
    'as'    => 'profile'
]);


Route::get('removeAccount', [
    'uses'  => 'entrepreneurshipController@removeAccount',
    'as'    => 'removeAccount'
]);

Route::get('terms', [
    'uses'  => 'entrepreneurshipController@terms',
    'as'    => 'terms'
]);

Route::get('sendEmail','Auth\PasswordController@getEmail');

Route::post('sendEmail', [ 
    'uses'  => 'Auth\PasswordController@postEmail',
    'as'    => 'sendEmail'
]);
// Route::post('sendEmail','Auth\PasswordController@postEmail');
Route::get('/password/reset/{token}','Auth\PasswordController@getReset');

Route::post('resetPassword/{token}', [ 
    'uses'  => 'Auth\PasswordController@postReset',
    'as'    => 'resetPassword'
]);


// API
Route::group(['prefix' => 'poderoso'], function()
{
    Route::get('/', [
        'uses'  => 'entrepreneurshipController@admin',
        'as'    => 'list'
    ]);

    Route::resource('entrepreneurships', 'entrepreneurshipController');


    Route::get('entrepreneurships/{id}/delete', [
        'uses' => 'entrepreneurshipController@destroy',
        'as' => 'poderoso.entrepreneurships.delete',
    ]);

    Route::get('editentrep/{id}', [ 
        'uses'  => 'entrepreneurshipController@edit',
        'as'    => 'editentrep'
    ]);

    Route::post('editentrep/{id}', [
        'uses'  => 'entrepreneurshipController@update',
        'as'    => 'editentrep'
    ]);



    Route::resource('categories', 'categoriesController');

    Route::get('categories/{id}/delete', [
        'as' => 'poderoso.categories.delete',
        'uses' => 'categoriesController@destroy',
    ]);

    Route::post('categories', [
        'as' => 'categories',
        'uses' => 'categoriesController@store',
    ]);

    Route::resource('cities', 'citiesController');

    Route::get('cities/{id}/delete', [
        'as' => 'poderoso.cities.delete',
        'uses' => 'citiesController@destroy',
    ]);

    Route::post('cities', [
        'as' => 'cities',
        'uses' => 'citiesController@store',
    ]);

    Route::resource('communes', 'communesController');

    Route::get('communes/{id}/delete', [
        'as' => 'poderoso.communes.delete',
        'uses' => 'communesController@destroy',
    ]);

    Route::post('communes', [
        'as' => 'communes',
        'uses' => 'communesController@store',
    ]);

    Route::resource('types', 'typesController');

    Route::get('types/{id}/delete', [
        'as' => 'poderoso.types.delete',
        'uses' => 'typesController@destroy',
    ]);

    Route::post('types', [
        'as' => 'types',
        'uses' => 'typesController@store',
    ]);
});

app/Models/communes.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

class communes extends Model
{
    
	public $table = "communes";
    

	public $fillable = [
	    "name",
		"slug"
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "name" => "string",
		"slug" => "string"
    ];

	public static $rules = [
	    "name" => "required"
	];

	public function entrepreneurships()
    {
        return $this->hasMany('App\Models\entrepreneurships','commune_id');
    }

}

app/Http/Controllers/communesController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreatecommunesRequest;
use App\Http\Requests\UpdatecommunesRequest;
use App\Libraries\Repositories\communesRepository;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use App\helpers\Helper as Helper;
use Response;
use App\Models\categories;
use App\Models\types;
use App\Models\cities;
use App\Models\communes;
use Illuminate\Support\Facades\Auth;

class communesController extends AppBaseController
{

	/** @var  communesRepository */
	private $communesRepository;

	function __construct(communesRepository $communesRepo)
	{
		$this->communesRepository = $communesRepo;
	}

	/**
	 * Display a listing of the communes.
	 *
	 * @return Response
	 */
	public function index()
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();
	        
			$communes = $this->communesRepository->paginate(10);

			return view('communes.index')->with('communes', $communes)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}	
	}

	/**
	 * Show the form for creating a new communes.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('communes.create');
	}

	/**
	 * Store a newly created communes in storage.
	 *
	 * @param CreatecommunesRequest $request
	 *
	 * @return Response
	 */
	public function store(CreatecommunesRequest $request)
	{
		$input = $request->all();
		$input['slug']=Helper::makeSlug($input['name']);

		$communes = $this->communesRepository->create($input);

		Flash::success('Comuna guardada correctamente.');

		return redirect(route('poderoso.communes.index'));
	}

	/**
	 * Display the specified communes.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$communes = $this->communesRepository->find($id);

		if(empty($communes))
		{
			Flash::error('Comuna no encontrada.');

			return redirect(route('poderoso.communes.index'));
		}

		return view('communes.show')->with('communes', $communes);
	}

	/**
	 * Show the form for editing the specified communes.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id)
	{
		if (Auth::user())
		{
			$cats = categories::all();
	        $typs = types::all();
	        $cits = cities::all();
	        $coms = communes::all();

			$communes = $this->communesRepository->find($id);

			if(empty($communes))
			{
				Flash::error('Comuna no encontrada.');

				return redirect(route('poderoso.communes.index'));
			}

			return view('communes.edit')->with('communes', $communes)->with('cats', $cats)->with('typs', $typs)->with('cits', $cits)->with('coms', $coms);
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}	
	}

	/**
	 * Update the specified communes in storage.
	 *
	 * @param  int              $id
	 * @param UpdatecommunesRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdatecommunesRequest $request)
	{
		$communes = $this->communesRepository->find($id);

		if(empty($communes))
		{
			Flash::error('Comuna no encontrada.');

			return redirect(route('poderoso.communes.index'));
		}

		$req = $request->all();
		$req['slug']=Helper::makeSlug($req['name']);
		
		$communes = $this->communesRepository->updateRich($req, $id);

		Flash::success('Comuna actualizada correctamente.');

		return redirect(route('poderoso.communes.index'));
	}

	/**
	 * Remove the specified communes from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		if (Auth::user())
		{

			$communes = $this->communesRepository->find($id);

			if(empty($communes))
			{
				Flash::error('Comuna no encontrada.');

				return redirect(route('poderoso.communes.index'));
			}

			$this->communesRepository->delete($id);

			Flash::success('Comuna eliminada correctamente');

			return redirect(route('poderoso.communes.index'));
		}
		else{

			return redirect(route('entrepreneurships.index'));

		}		
	}
}

resources/views/communes/create.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'communes.store']) !!}

        @include('communes.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/communes/edit.blade.php
@extends('layout')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($communes, ['route' => ['poderoso.communes.update', $communes->id], 'method' => 'patch']) !!}

        @include('communes.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/communes/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('name', 'Name:') !!}
	{!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/communes/index.blade.php
@extends('layout')

@section('content')
@include('menu.admin_menu')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Communes
        </div>
        <div class="panel-body">
            <div class="row">
                @include('flash::message')
            </div>

            <div class="row">
                @if($communes->isEmpty())
                    <div class="well text-center">Comunas no encontradas.</div>
                @else
                <div class="col-lg-12">
                    @include('communes.table')
                </div>
                @endif
            </div>

            @include('common.paginate', ['records' => $communes])

        </div>
    </div>

    <form class="form-horizontal" role="form" method="POST" action="{{ route('communes') }}">
        @include('partials/errors')
        <div class="panel panel-default">
            <div class="panel-heading">@lang('auth.register_title')</div>
            <div class="panel-body">

                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label class="col-md-4 control-label">@lang('validation.attributes.name')</label>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-5">
                        <button type="submit" class="btn btn-primary">
                            @lang('auth.register_button')
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
    </form>
</div>
@endsection

resources/views/communes/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('communes.show_fields')
</div>
@endsection

resources/views/communes/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $communes->name !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{!! $communes->slug !!}</p>
</div>

resources/views/communes/table.blade.php
<table class="table">
    <thead>
    <th>Name</th>
			<th>Slug</th>
    <th width="50px">Action</th>
    </thead>
    <tbody>
    @foreach($communes as $communes)
        <tr>
            <td>{!! $communes->name !!}</td>
			<td>{!! $communes->slug !!}</td>
            <td>
                <a href="{!! route('poderoso.communes.edit', [$communes->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('poderoso.communes.delete', [$communes->id]) !!}" onclick="return confirm('¿Está seguro que desea eliminar esta comuna?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>